'Global information in database
Global Vas
Global Fs
Global Qts
Global Re
Global Zmax
Global Tvb
Global Tfs
Global F1
Global F2

Global F3
Global Vb
Global Ro

  'diameter in inches
Global ACDI
  
  'peak to peak driver excursion
Global EXCI
  
  'maximum input in watts RMS
Global WRMS
  
Global BeenHere

Sub CenterForm (F As Form)
   F.Left = (Screen.Width - F.Width) / 2
   F.Top = (Screen.Height - F.Height) / 2
End Sub

